//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesoWeb
    {
        public int IdAccedo { get; set; }
        public bool EsMenu { get; set; }
        public string Id { get; set; }
        public string Caption { get; set; }
        public string MenuPadre { get; set; }
        public string Clase { get; set; }
        public string Usuario { get; set; }
        public string Modulo { get; set; }
        public bool Activo { get; set; }
    }
}
