//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodegaSerie
    {
        public int IdBodegaSerie { get; set; }
        public string CodBodega { get; set; }
        public string Serie { get; set; }
        public string CodUnion { get; set; }
        public string SerieUnion { get; set; }
        public bool EsFact { get; set; }
        public bool EsColector { get; set; }
        public bool EsPedido { get; set; }
        public bool EsCaja { get; set; }
        public bool EsRequisa { get; set; }
        public bool EsInv { get; set; }
        public bool EsExport { get; set; }
        public bool EsImport { get; set; }
        public bool EsPlaneacion { get; set; }
        public bool EsConsignacion { get; set; }
    }
}
