//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonificaciones
    {
        public int IdEscala { get; set; }
        public int IdTipoBonif { get; set; }
        public string CodBodega { get; set; }
        public string CodigoProducto { get; set; }
        public int IdProducto { get; set; }
        public int CantMin { get; set; }
        public int Bonificar { get; set; }
        public string CodigoCliente { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string CodProdBonifica { get; set; }
        public int IdProdBonifica { get; set; }
        public decimal AsumEmpresa { get; set; }
        public decimal AsumProv { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinaliza { get; set; }
        public bool Activo { get; set; }
        public int IdUsuarioCrea { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioInactiva { get; set; }
        public Nullable<System.DateTime> FechaInactivo { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
