//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonificacionExcluirLab
    {
        public int IdExcBonif { get; set; }
        public string CodProveedor { get; set; }
        public Nullable<bool> EsPublico { get; set; }
        public Nullable<bool> Esditribuidor { get; set; }
        public Nullable<bool> EsEspecial { get; set; }
    }
}
