//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteTienda
    {
        public int IdCteTienda { get; set; }
        public string CodigoCliente { get; set; }
        public int IdBodega { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public bool Activo { get; set; }
        public int IdUsuarioCrea { get; set; }
        public Nullable<int> IdUsuarioInactiva { get; set; }
    }
}
