//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorreoAutorizaFactura
    {
        public int IdCorreoAutoriza { get; set; }
        public string Correo { get; set; }
        public bool AntAutorizar { get; set; }
        public bool DespAutorizar { get; set; }
    }
}
