//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaVenta
    {
        public int IdFactura { get; set; }
        public Nullable<int> IdProforma { get; set; }
        public int IdBodega { get; set; }
        public string IdSerie { get; set; }
        public string NoFactura { get; set; }
        public string CodCliente { get; set; }
        public string NomCliente { get; set; }
        public string Nombre { get; set; }
        public string Ruc { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public int IdVendedor { get; set; }
        public string NomVendedor { get; set; }
        public string TipoVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Plazo { get; set; }
        public System.DateTime Vence { get; set; }
        public int DiasGracia { get; set; }
        public string IdMoneda { get; set; }
        public decimal TasaCambio { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public decimal Total { get; set; }
        public decimal TotalDolar { get; set; }
        public decimal TotalCordoba { get; set; }
        public string DireccionEntrega { get; set; }
        public string Observaciones { get; set; }
        public bool Exportacion { get; set; }
        public bool Exoneracion { get; set; }
        public string NoExoneracion { get; set; }
        public string MotivoAnulacion { get; set; }
        public string OrdenCompra { get; set; }
        public bool ContraEntrega { get; set; }
        public bool EsDelivery { get; set; }
        public Nullable<int> IdVendedorClave { get; set; }
        public string Estado { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdUsuarioAnula { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<int> IdUsuarioCaja { get; set; }
        public string Longitud { get; set; }
        public string Latitud { get; set; }
        public Nullable<bool> EsCentralizacion { get; set; }
    }
}
