//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public int IdParametro { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> IdCentroCostoDefecto { get; set; }
        public string MonedaLocal { get; set; }
        public string MonedaExtranjera { get; set; }
        public string MonedaLocalDes { get; set; }
        public string MonedaExtranjeraDes { get; set; }
        public Nullable<int> Niveles { get; set; }
        public Nullable<bool> CierresInicioFinMes { get; set; }
        public Nullable<int> CuentaAjusteAmor { get; set; }
        public Nullable<int> IdAsientoAmortizacion { get; set; }
        public Nullable<int> IdAsientoCXP { get; set; }
        public Nullable<int> CuentaIVAAcreditable { get; set; }
        public Nullable<int> CuentaIVAPagar { get; set; }
        public Nullable<decimal> PorcImpuestoAcreditable { get; set; }
        public Nullable<decimal> MinimoRetencion { get; set; }
        public Nullable<int> CuentaIMI { get; set; }
        public Nullable<decimal> PorcentajeIMI { get; set; }
        public Nullable<decimal> NomPorcEmpleado { get; set; }
        public Nullable<decimal> NomPorcPatronal { get; set; }
        public Nullable<decimal> PorcSubsComp { get; set; }
        public string MonedaFacturacion { get; set; }
        public Nullable<decimal> TasaFacturacion { get; set; }
        public Nullable<int> PlazoProforma { get; set; }
        public string TasaNotas { get; set; }
        public Nullable<int> DiferencialGanancia { get; set; }
        public Nullable<int> DiferencialPerdida { get; set; }
        public Nullable<int> UltimaOrdenCompra { get; set; }
        public byte[] LogoEmpresa { get; set; }
        public string RRHH { get; set; }
        public byte[] ImgCumple { get; set; }
    }
}
