//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int IdProveedor { get; set; }
        public string TipoProveedor { get; set; }
        public int IdCategoria { get; set; }
        public string Codigo { get; set; }
        public string Proveedor1 { get; set; }
        public string NombreComercial { get; set; }
        public string RUC { get; set; }
        public string Beneficiario { get; set; }
        public Nullable<int> Nacionalidad { get; set; }
        public Nullable<int> IdPais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> MonedaID { get; set; }
        public int LimiteCredito { get; set; }
        public bool CongelarPago { get; set; }
        public bool IR { get; set; }
        public bool IMI { get; set; }
        public bool IVA { get; set; }
        public string TextoCK { get; set; }
        public Nullable<int> Transito { get; set; }
        public Nullable<int> TiempoMinInv { get; set; }
        public string CUENTAXPAGAR { get; set; }
        public string CUENTAANTICIPO { get; set; }
        public string CUENTAVARIOS { get; set; }
        public string CUENTACONTADO { get; set; }
        public string CuentaBonificaciones { get; set; }
        public string CuentaIngresoDiferencial { get; set; }
        public string CuentaEgresoDiferencial { get; set; }
        public bool Activo { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<int> IDIR { get; set; }
        public System.DateTime CREFCH { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string WebSite { get; set; }
        public string IdCiudad { get; set; }
        public string CONTACTO { get; set; }
        public string CARGO { get; set; }
        public string CONVENCIONALCONTACTO { get; set; }
        public string MOVILCONTACTO { get; set; }
        public string EMAILCONTACTO { get; set; }
        public string CIUDADCONTACTO { get; set; }
        public Nullable<int> PAISCONTACTO { get; set; }
        public string CONTACTO2 { get; set; }
        public string CARGOCONTACTO2 { get; set; }
        public string CONVENCIONALCONTACTO2 { get; set; }
        public string MOVILCONTACTO2 { get; set; }
        public string EMAILCONTACTO2 { get; set; }
        public string CIUDADCONTACTO2 { get; set; }
        public Nullable<int> PAISCONTACTO2 { get; set; }
        public string CONTACTO3 { get; set; }
        public string CARGOCONTACTO3 { get; set; }
        public string CONVENCIONALCONTACTO3 { get; set; }
        public string MOVILCONTACTO3 { get; set; }
        public string EMAILCONTACTO3 { get; set; }
        public string CIUDADCONTACTO3 { get; set; }
        public Nullable<int> PAISCONTACTO3 { get; set; }
    }
}
