//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisaDetalle
    {
        public System.Guid IdRequisaDet { get; set; }
        public System.Guid IdRequisa { get; set; }
        public int Index { get; set; }
        public string CodigoProducto { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public string Ubicacion { get; set; }
        public string CodBodega { get; set; }
        public int Existencia { get; set; }
        public string CodBodegaDestino { get; set; }
        public int ExistenciaDestinoL { get; set; }
        public int ExistenciaDestino { get; set; }
        public string NoLote { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public int Cantidad { get; set; }
        public bool ControladoPorLote { get; set; }
    
        public virtual Requisa Requisa { get; set; }
    }
}
