//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisa()
        {
            this.RequisaDetalle = new HashSet<RequisaDetalle>();
        }
    
        public System.Guid IdRequisa { get; set; }
        public string Serie { get; set; }
        public string NoRequisa { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NoPedido { get; set; }
        public string CodBodega { get; set; }
        public string CodBodegaDestino { get; set; }
        public string Observaciones { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdUsuarioModifica { get; set; }
        public System.DateTime FechaModifica { get; set; }
        public bool EnProceso { get; set; }
        public bool Transito { get; set; }
        public bool Anulado { get; set; }
        public Nullable<int> IdUsuarioAnula { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisaDetalle> RequisaDetalle { get; set; }
    }
}
