//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public string IdSerie { get; set; }
        public int Factura { get; set; }
        public int Recibo { get; set; }
        public int Colector { get; set; }
        public int Inventario { get; set; }
        public int Ticket { get; set; }
        public int Pedido { get; set; }
        public int Requisa { get; set; }
        public int Proforma { get; set; }
        public int Garantia { get; set; }
        public int OT { get; set; }
        public int ProformaProv { get; set; }
        public int Remision { get; set; }
        public int Abaste { get; set; }
        public int Anexos { get; set; }
    }
}
