//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaDetalle
    {
        public System.Guid IdVentaDetalle { get; set; }
        public System.Guid IdVenta { get; set; }
        public int Index { get; set; }
        public string Codigo { get; set; }
        public string Producto { get; set; }
        public decimal Precio { get; set; }
        public decimal PrecioCordoba { get; set; }
        public decimal PrecioDolar { get; set; }
        public decimal PorcDescuento { get; set; }
        public decimal PorcDescuentoAdicional { get; set; }
        public decimal PorcImpuesto { get; set; }
        public int Cantidad { get; set; }
        public decimal SubTotal { get; set; }
        public decimal SubTotalCordoba { get; set; }
        public decimal SubTotalDolar { get; set; }
        public decimal Descuento { get; set; }
        public decimal DescuentoCordoba { get; set; }
        public decimal DescuentoDolar { get; set; }
        public decimal DescuentoAdicional { get; set; }
        public decimal DescuentoAdicionalCordoba { get; set; }
        public decimal DescuentoAdicionalDolar { get; set; }
        public decimal SubTotalNeto { get; set; }
        public decimal SubTotalNetoCordoba { get; set; }
        public decimal SubTotalNetoDolar { get; set; }
        public decimal Impuesto { get; set; }
        public decimal ImpuestoCordoba { get; set; }
        public decimal ImpuestoDolar { get; set; }
        public decimal ImpuestoExo { get; set; }
        public decimal ImpuestoExoCordoba { get; set; }
        public decimal ImpuestoExoDolar { get; set; }
        public decimal Total { get; set; }
        public decimal TotalCordoba { get; set; }
        public decimal TotalDolar { get; set; }
        public bool EsBonif { get; set; }
        public bool EsBonifLibre { get; set; }
        public bool EsExonerado { get; set; }
        public bool EsExento { get; set; }
        public bool PrecioLiberado { get; set; }
        public decimal Margen { get; set; }
        public bool PedirAutorizado { get; set; }
        public bool Autorizado { get; set; }
        public string UsuarioAutoriza { get; set; }
        public int IndexUnion { get; set; }
    
        public virtual Venta Venta { get; set; }
    }
}
