//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GV_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BalancesEntities : DbContext
    {
        public BalancesEntities()
            : base("name=BalancesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bodegas> Bodegas { get; set; }
        public virtual DbSet<Estaciones> Estaciones { get; set; }
        public virtual DbSet<Serie> Serie { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosBodegas> UsuariosBodegas { get; set; }
        public virtual DbSet<BodegaSerie> BodegaSerie { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Impuestos> Impuestos { get; set; }
        public virtual DbSet<LiberarPrecio> LiberarPrecio { get; set; }
        public virtual DbSet<ConceptoPrecio> ConceptoPrecio { get; set; }
        public virtual DbSet<BodegaLaboratorioKardex> BodegaLaboratorioKardex { get; set; }
        public virtual DbSet<Kardex> Kardex { get; set; }
        public virtual DbSet<Bonificaciones> Bonificaciones { get; set; }
        public virtual DbSet<PrecioVenta> PrecioVenta { get; set; }
        public virtual DbSet<PrecioVentaEscala> PrecioVentaEscala { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Descuentos> Descuentos { get; set; }
        public virtual DbSet<DireccionCliente> DireccionCliente { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<CorreoAutorizaFactura> CorreoAutorizaFactura { get; set; }
        public virtual DbSet<PermisoFactura> PermisoFactura { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<VentaDetalle> VentaDetalle { get; set; }
        public virtual DbSet<LiberarBonificacion> LiberarBonificacion { get; set; }
    }
}
