//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GV_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo
    {
        public string SSSCTA { get; set; }
        public string DESCTA { get; set; }
        public string UNIDAD { get; set; }
        public string GRUPO { get; set; }
        public string SUBGRUPO { get; set; }
        public Nullable<double> PESOUM { get; set; }
        public bool COBIVA { get; set; }
        public Nullable<decimal> EXISTENCIAS { get; set; }
        public Nullable<decimal> VALOREXISTENCIAS { get; set; }
        public Nullable<decimal> EXISTENCIASCERRADA { get; set; }
        public Nullable<decimal> VALOREXISTENCIASCERRADA { get; set; }
        public decimal COSPRO { get; set; }
        public double COSPRO_CE { get; set; }
        public bool FUERADELINEA { get; set; }
        public string CLASE { get; set; }
        public bool FACTURAR { get; set; }
        public decimal COSTOH { get; set; }
        public Nullable<decimal> FLUCTUACION { get; set; }
        public Nullable<bool> LIBERAR { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> COSTOHH { get; set; }
        public string Presentacion { get; set; }
        public string CodigoProveedor { get; set; }
        public bool EnLiquidacion { get; set; }
        public bool Bonificable { get; set; }
        public decimal UnitarioProveedor { get; set; }
        public string GrupoPresu { get; set; }
        public string Clasificacion { get; set; }
        public string DescripcionProveedor { get; set; }
        public bool BonificarSiempre { get; set; }
        public int UnidadesBonificables { get; set; }
        public Nullable<bool> Estrategico { get; set; }
    }
}
