//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GV_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public string CODCTA { get; set; }
        public string DESCTA { get; set; }
        public string DIRECC { get; set; }
        public string DPTO { get; set; }
        public string COD { get; set; }
        public string CONTAC { get; set; }
        public string TELEFO { get; set; }
        public string TELEFONO1 { get; set; }
        public string CARGOP { get; set; }
        public string Plazo { get; set; }
        public string Vendedor { get; set; }
        public string Municipio { get; set; }
        public decimal Techo { get; set; }
        public string Observaciones { get; set; }
        public bool Exonerado { get; set; }
        public bool FacturarVencido { get; set; }
        public bool SinCredito { get; set; }
        public decimal Descuento { get; set; }
        public bool Liquidar { get; set; }
        public bool Distribuidor { get; set; }
        public string Bodega { get; set; }
        public bool Especial { get; set; }
        public string Sector { get; set; }
        public Nullable<System.DateTime> UltimaFechaPago { get; set; }
        public decimal UltimoPago { get; set; }
        public string ReciboUltimoPago { get; set; }
        public string BodegaProceso { get; set; }
        public bool Clave { get; set; }
        public string Lista { get; set; }
        public string Cedula { get; set; }
        public string Direccnegocio { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public string Moneda { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public string RazonSocial { get; set; }
        public int Gracia { get; set; }
    }
}
