//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GV_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguraFacturacion
    {
        public string Serie { get; set; }
        public string Bodegas { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public string ClienteContado { get; set; }
        public string EmiteFactura { get; set; }
        public Nullable<short> Recibo { get; set; }
        public Nullable<short> Colector { get; set; }
        public string Vendedor { get; set; }
        public string PorDefecto { get; set; }
        public string EsdeRuta { get; set; }
    }
}
