//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GV_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlInventario
    {
        public string Serie { get; set; }
        public string Bodegas { get; set; }
        public int Secuencia { get; set; }
        public int Requisa { get; set; }
        public int Compras { get; set; }
    }
}
