//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GV_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        public string CodiProd { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string Documento { get; set; }
        public decimal Entrada { get; set; }
        public decimal Salidas { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public string tipofactura { get; set; }
        public Nullable<decimal> Valorentrada { get; set; }
        public Nullable<decimal> Valorsalida { get; set; }
        public Nullable<decimal> SaldoValor { get; set; }
        public Nullable<decimal> Orden { get; set; }
        public string Bodega { get; set; }
        public Nullable<bool> Cerrada { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public string Nolote { get; set; }
        public string BodegaDestino { get; set; }
    }
}
