//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GV_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbBodega
    {
        public string Codigo { get; set; }
        public string titulo { get; set; }
        public string SCta { get; set; }
        public string CuentaIngContado { get; set; }
        public string CuentaIngCredito { get; set; }
        public string CuentaCajaCordoba { get; set; }
        public string CuentaCajaDolares { get; set; }
        public string CuentaCostos { get; set; }
        public string CuentaInven { get; set; }
        public string ComisionTarjeta { get; set; }
        public string CuentaDevoluciones { get; set; }
    }
}
