//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GV_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public byte[] Pass { get; set; }
        public Nullable<int> IdRol { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public bool AccesoWeb { get; set; }
        public Nullable<bool> ColaImpresionWeb { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public bool Desconectar { get; set; }
        public bool Lotificar { get; set; }
    }
}
